/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.epn.vista;

import com.epn.componentes.Imagen;
import com.epn.componentes.Validaciones;
import com.epn.correlaciones.Datos;
import com.epn.correlaciones.Glasso;
import com.epn.correlaciones.Manucci;
import com.epn.correlaciones.Kartoatmodjo;
import com.epn.correlaciones.Muhammad;
import com.epn.correlaciones.Standing;
import com.epn.correlaciones.Total;
import com.epn.correlaciones.Vasquez;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

//Comentario Kevinn*****


/**
 *
 * @author valer
 */

public class Bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    
    Datos datos=new Datos();
    Validaciones validar = new Validaciones();
    
    Standing constructorS;
    Vasquez constructorV;
    Glasso constructorG;
    Manucci constructorM;
    Total constructorT;
    Kartoatmodjo constructorKa;
    Muhammad constructorMu;

    
    public double Py, Ty, RGP,rg, API, Psep, Tsep, Na;

    String path1 = "MTXX_MH20230402_200829794.jpg";
    public Bienvenida() {
        initComponents();
        Imagen img = new Imagen();
        img.mostrarImagenes(JImagen1,path1);
        
    }
    public void cargar(){
    JTpy.setText(String.valueOf(Py));
    JTapi.setText(String.valueOf(API));
    JTty.setText(String.valueOf(Ty));
    JTrg.setText(String.valueOf(rg));
    JTpsep.setText(String.valueOf(Psep));
    JTtsep.setText(String.valueOf(Tsep));
    JTna.setText(String.valueOf(Na));
    JTrgp.setText(String.valueOf(RGP));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JTpy = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTty = new javax.swing.JTextField();
        JTrgp = new javax.swing.JTextField();
        JTrg = new javax.swing.JTextField();
        JTapi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JTpsep = new javax.swing.JTextField();
        JTtsep = new javax.swing.JTextField();
        JTna = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTOrden = new javax.swing.JLabel();
        JRBstanding = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        JRBvasquez = new javax.swing.JRadioButton();
        JRBglasso = new javax.swing.JRadioButton();
        JRBmanucci = new javax.swing.JRadioButton();
        JRBtotal = new javax.swing.JRadioButton();
        JRBmuhammad = new javax.swing.JRadioButton();
        JRBkartoatmodjo = new javax.swing.JRadioButton();
        JImagen1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Presión de yacimiento [Py]");

        JTpy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTpyActionPerformed(evt);
            }
        });
        JTpy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTpyKeyTyped(evt);
            }
        });

        jLabel10.setText("[Lpaca]");

        jLabel3.setText("Temperatura de yacimiento [Ty]");

        jLabel4.setText("Relación gas petróleo [RGP]");

        jLabel5.setText("Gravedad especifica del gas [ϒg]");

        jLabel6.setText("Gravedad especifica del petroleo [API]");

        JTty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTtyActionPerformed(evt);
            }
        });
        JTty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTtyKeyTyped(evt);
            }
        });

        JTrgp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTrgpKeyTyped(evt);
            }
        });

        JTrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTrgKeyTyped(evt);
            }
        });

        JTapi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTapiKeyTyped(evt);
            }
        });

        jLabel11.setText("[°F]");

        jLabel12.setText("[adimensional]");

        jLabel13.setText("[PCN/BN]");

        jLabel14.setText("[adimensional]");

        jLabel7.setText("Presión del separador [Psep]");

        jLabel8.setText("Temperatura del separador [Tsep]");

        jLabel9.setText("Salinidad [Na]");

        JTpsep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTpsepKeyTyped(evt);
            }
        });

        JTtsep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTtsepKeyTyped(evt);
            }
        });

        JTna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTnaKeyTyped(evt);
            }
        });

        jLabel15.setText("[Lpaca]");

        jLabel16.setText("[°F]");

        jLabel17.setText("[ppm]");

        jTOrden.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jTOrden.setText("Seleccione la correlación que desee usar");
        jTOrden.setAlignmentX(0.5F);

        JRBstanding.setText("Standing");
        JRBstanding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBstandingActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel18.setText("Correlaciones PVT");
        jLabel18.setAlignmentX(0.5F);

        JRBvasquez.setText("Vasquez y Beggs");
        JRBvasquez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBvasquezActionPerformed(evt);
            }
        });

        JRBglasso.setText("Glasso");
        JRBglasso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBglassoActionPerformed(evt);
            }
        });

        JRBmanucci.setText("Manucci y Rosales");
        JRBmanucci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBmanucciActionPerformed(evt);
            }
        });

        JRBtotal.setText("Total");
        JRBtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBtotalActionPerformed(evt);
            }
        });

        JRBmuhammad.setText("Muhammad Ali Al-Marhoun");
        JRBmuhammad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBmuhammadActionPerformed(evt);
            }
        });

        JRBkartoatmodjo.setText("Kartoatmodjo y Schmidt");
        JRBkartoatmodjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBkartoatmodjoActionPerformed(evt);
            }
        });

        JImagen1.setText("jLabel19");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTpy, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTrg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTrgp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTty, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTapi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTna, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTtsep, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTpsep, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15))
                .addGap(115, 115, 115))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JRBkartoatmodjo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRBtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRBmanucci, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRBmuhammad)
                            .addComponent(JRBglasso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRBstanding, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRBvasquez))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(JTpsep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(JTtsep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(JTna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTpy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel2))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTrgp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTapi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel14))))
                        .addGap(30, 30, 30)
                        .addComponent(jTOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JRBstanding)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JRBvasquez)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JRBglasso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JRBmanucci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JRBtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JRBmuhammad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRBkartoatmodjo)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addGap(502, 502, 502)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTpyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTpyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTpyActionPerformed

    private void JTtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTtyActionPerformed

    private void JRBvasquezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBvasquezActionPerformed
                VasquezFront vasquezFront = new VasquezFront();
                leerDatos();
                constructorV=new Vasquez(Py,Ty,RGP,rg,API,Psep,Tsep,Na);
                vasquezFront.Py=constructorV.getPy();
                vasquezFront.API=constructorV.getAPI();
                vasquezFront.Ty=constructorV.getTy();
                vasquezFront.Na=constructorV.getNa();
                vasquezFront.Psep=constructorV.getPsep();
                vasquezFront.Tsep=constructorV.getTsep();
                vasquezFront.rg=constructorV.getRg();
                vasquezFront.RGP=constructorV.getRGP();
                
                
                vasquezFront.setVisible(true);
                vasquezFront.cargar();
                dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_JRBvasquezActionPerformed

    private void JRBglassoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBglassoActionPerformed
                GlassoFront glassoFront = new GlassoFront();
                leerDatos();
                constructorG=new Glasso(Py,Ty,RGP,rg,API,Psep,Tsep,Na);
                glassoFront.Py=constructorG.getPy();
                glassoFront.API=constructorG.getAPI();
                glassoFront.Ty=constructorG.getTy();
                glassoFront.Na=constructorG.getNa();
                glassoFront.Psep=constructorG.getPsep();
                glassoFront.Tsep=constructorG.getTsep();
                glassoFront.rg=constructorG.getRg();
                glassoFront.RGP=constructorG.getRGP();
                
                
                glassoFront.setVisible(true);
                glassoFront.cargar();
                dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_JRBglassoActionPerformed

    private void JRBmanucciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBmanucciActionPerformed
             ManucciFront manucciFront = new ManucciFront();
                leerDatos();
                constructorM=new Manucci(Py,Ty,RGP,rg,API,Psep,Tsep,Na);
                manucciFront.Py=constructorM.getPy();
                manucciFront.API=constructorM.getAPI();
                manucciFront.Ty=constructorM.getTy();
                manucciFront.Na=constructorM.getNa();
                manucciFront.Psep=constructorM.getPsep();
                manucciFront.Tsep=constructorM.getTsep();
                manucciFront.rg=constructorM.getRg();
                manucciFront.RGP=constructorM.getRGP();
                
                
                manucciFront.setVisible(true);
                manucciFront.cargar();
                dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_JRBmanucciActionPerformed

    private void JRBtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBtotalActionPerformed
        TotalFront totalFront = new TotalFront();
                leerDatos();
                constructorT=new Total(Py,Ty,RGP,rg,API,Psep,Tsep,Na);
                totalFront.Py=constructorT.getPy();
                totalFront.API=constructorT.getAPI();
                totalFront.Ty=constructorT.getTy();
                totalFront.Na=constructorT.getNa();
                totalFront.Psep=constructorT.getPsep();
                totalFront.Tsep=constructorT.getTsep();
                totalFront.rg=constructorT.getRg();
                totalFront.RGP=constructorT.getRGP();
                
                
                totalFront.setVisible(true);
                totalFront.cargar();
                dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBtotalActionPerformed

    private void JRBmuhammadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBmuhammadActionPerformed
        MuhammadFront muhammadFront = new MuhammadFront();
                leerDatos();
                constructorMu=new Muhammad(Py,Ty,RGP,rg,API,Psep,Tsep,Na);
                muhammadFront.Py=constructorMu.getPy();
                muhammadFront.API=constructorMu.getAPI();
                muhammadFront.Ty=constructorMu.getTy();
                muhammadFront.Na=constructorMu.getNa();
                muhammadFront.Psep=constructorMu.getPsep();
                muhammadFront.Tsep=constructorMu.getTsep();
                muhammadFront.rg=constructorMu.getRg();
                muhammadFront.RGP=constructorMu.getRGP();
                
                
                muhammadFront.setVisible(true);
                muhammadFront.cargar();
                dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBmuhammadActionPerformed

    private void JRBkartoatmodjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBkartoatmodjoActionPerformed
         /*KartoatmodjoFront kartoFront = new KartoatmodjoFront();
                leerDatos();
                constructorKa=new Kartoatmodjo(Py,Ty,RGP,rg,API,Psep,Tsep,Na);
                kartoFront.Py=constructorKa.getPy();
                kartoFront.API=constructorKa.getAPI();
                kartoFront.Ty=constructorKa.getTy();
                kartoFront.Na=constructorKa.getNa();
                kartoFront.Psep=constructorKa.getPsep();
                kartoFront.Tsep=constructorKa.getTsep();
                kartoFront.rg=constructorKa.getRg();
                kartoFront.RGP=constructorKa.getRGP();
                
                
                kartoFront.setVisible(true);
                kartoFront.cargar();*/
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBkartoatmodjoActionPerformed

    private void JRBstandingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBstandingActionPerformed
               StandingFront standFront = new StandingFront();
                leerDatos();
                constructorS=new Standing(Py,Ty,RGP,rg,API,Psep,Tsep,Na);
                standFront.Py=constructorS.getPy();
                standFront.API=constructorS.getAPI();
                standFront.Ty=constructorS.getTy();
                standFront.Na=constructorS.getNa();
                standFront.Psep=constructorS.getPsep();
                standFront.Tsep=constructorS.getTsep();
                standFront.rg=constructorS.getRg();
                standFront.RGP=constructorS.getRGP();
                
                
                standFront.setVisible(true);
                standFront.cargar();
                dispose();
          
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBstandingActionPerformed

    private void JTpyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTpyKeyTyped
        validar.validarNumeros(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_JTpyKeyTyped

    private void JTtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTtyKeyTyped
        validar.validarNumeros(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_JTtyKeyTyped

    private void JTrgpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTrgpKeyTyped
        validar.validarNumeros(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_JTrgpKeyTyped

    private void JTrgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTrgKeyTyped
        validar.validarNumeros(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_JTrgKeyTyped

    private void JTapiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTapiKeyTyped
        validar.validarNumeros(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_JTapiKeyTyped

    private void JTpsepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTpsepKeyTyped
        validar.validarNumeros(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_JTpsepKeyTyped

    private void JTtsepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTtsepKeyTyped
        validar.validarNumeros(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_JTtsepKeyTyped

    private void JTnaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTnaKeyTyped
        validar.validarNumeros(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnaKeyTyped
public void leerDatos(){
        Py=Double.parseDouble(JTpy.getText());
                 Ty=Double.parseDouble(JTty.getText());
                 RGP=Double.parseDouble(JTrgp.getText());
                 rg=Double.parseDouble(JTrg.getText());
                 API=Double.parseDouble(JTapi.getText());
                 Psep=Double.parseDouble(JTpsep.getText());
                 Tsep=Double.parseDouble(JTtsep.getText());
                 Na=Double.parseDouble(JTna.getText());
               
    }
//public JTextField getJTpy() { return JTpy; }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JImagen1;
    private javax.swing.JRadioButton JRBglasso;
    private javax.swing.JRadioButton JRBkartoatmodjo;
    private javax.swing.JRadioButton JRBmanucci;
    private javax.swing.JRadioButton JRBmuhammad;
    private javax.swing.JRadioButton JRBstanding;
    private javax.swing.JRadioButton JRBtotal;
    private javax.swing.JRadioButton JRBvasquez;
    private javax.swing.JTextField JTapi;
    private javax.swing.JTextField JTna;
    private javax.swing.JTextField JTpsep;
    private javax.swing.JTextField JTpy;
    private javax.swing.JTextField JTrg;
    private javax.swing.JTextField JTrgp;
    private javax.swing.JTextField JTtsep;
    private javax.swing.JTextField JTty;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTOrden;
    // End of variables declaration//GEN-END:variables
}
